// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZ4qfeYWeUeaKHLHroL_isFOaorxSdg8',
    appId: '1:483898678133:web:57b08e9268c7e994c8d13c',
    messagingSenderId: '483898678133',
    projectId: 'guess-1cf0a',
    authDomain: 'guess-1cf0a.firebaseapp.com',
    storageBucket: 'guess-1cf0a.appspot.com',
    measurementId: 'G-1HB917NHFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIygw8yy7tdUVarfxFaIF3KGwJiA91zig',
    appId: '1:483898678133:android:532ad6a6755a5d6ac8d13c',
    messagingSenderId: '483898678133',
    projectId: 'guess-1cf0a',
    storageBucket: 'guess-1cf0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeu8Tw6zoZaWbeCriAz_2gRqV-nF03mlM',
    appId: '1:483898678133:ios:0f6518b7a6c607d0c8d13c',
    messagingSenderId: '483898678133',
    projectId: 'guess-1cf0a',
    storageBucket: 'guess-1cf0a.appspot.com',
    iosBundleId: 'com.example.guessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeu8Tw6zoZaWbeCriAz_2gRqV-nF03mlM',
    appId: '1:483898678133:ios:0f6518b7a6c607d0c8d13c',
    messagingSenderId: '483898678133',
    projectId: 'guess-1cf0a',
    storageBucket: 'guess-1cf0a.appspot.com',
    iosBundleId: 'com.example.guessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZ4qfeYWeUeaKHLHroL_isFOaorxSdg8',
    appId: '1:483898678133:web:9f527e48647d19bcc8d13c',
    messagingSenderId: '483898678133',
    projectId: 'guess-1cf0a',
    authDomain: 'guess-1cf0a.firebaseapp.com',
    storageBucket: 'guess-1cf0a.appspot.com',
    measurementId: 'G-3QPRFYTGC0',
  );
}
